"""updated_fields

Revision ID: 32fc730e1667
Revises: a325ff7423fb
Create Date: 2025-08-31 09:38:31.351865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '32fc730e1667'
down_revision: Union[str, None] = 'a325ff7423fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('subtitle', sa.TEXT(), nullable=True))
    op.add_column('books', sa.Column('thumbnail', sa.TEXT(), nullable=True))
    op.add_column('books', sa.Column('published', sa.DATE(), nullable=True))
    op.add_column('books', sa.Column('pages', sa.BIGINT(), nullable=True))
    op.alter_column('books', 'description',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('books', 'page_count')
    op.drop_column('books', 'published_date')
    op.drop_column('books', 'cover_image')
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('users', 'image',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'image',
               existing_type=sa.TEXT(),
               type_=sa.VARCHAR(length=300),
               existing_nullable=True)
    op.alter_column('users', 'password',
               existing_type=sa.TEXT(),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
    op.add_column('books', sa.Column('cover_image', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('books', sa.Column('published_date', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('books', sa.Column('page_count', sa.BIGINT(), autoincrement=False, nullable=True))
    op.alter_column('books', 'description',
               existing_type=sa.TEXT(),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    op.drop_column('books', 'pages')
    op.drop_column('books', 'published')
    op.drop_column('books', 'thumbnail')
    op.drop_column('books', 'subtitle')
    # ### end Alembic commands ###
