"""updated fields

Revision ID: ceb25a5f8d76
Revises: 451037d920fb
Create Date: 2025-09-04 08:10:06.637843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ceb25a5f8d76'
down_revision: Union[str, None] = '451037d920fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reviews', 'rating',
               existing_type=sa.INTEGER(),
               type_=sa.FLOAT(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reviews', 'rating',
               existing_type=sa.FLOAT(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
