"""updated model

Revision ID: e78d3d86dff0
Revises: 32fc730e1667
Create Date: 2025-09-01 09:25:05.017928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e78d3d86dff0'
down_revision: Union[str, None] = '32fc730e1667'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books', 'author',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('books', 'published',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books', 'published',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('books', 'author',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###
